# Creates an entry in html/changelogs automatically, to eventually be compiled by compile_changelogs
name: SS1984 DreamChecker
on:
  - pull_request_target
jobs:
  dreamchecker:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Restore SpacemanDMM cache
      uses: actions/cache@v4
      with:
        path: ~/SpacemanDMM
        key: ${{ runner.os }}-spacemandmm-${{ hashFiles('dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-spacemandmm-
    - name: Setup Node
      uses: ./.github/actions/setup_node
      with:
        restore-yarn-cache: true
    - name: Restore Bootstrap cache
      uses: actions/cache@v4
      with:
        path: tools/bootstrap/.cache
        key: ${{ runner.os }}-bootstrap-${{ hashFiles('tools/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-bootstrap-
    - name: Install DreamChecker
      run: |
        pip3 install setuptools
        bash tools/ci/install_spaceman_dmm.sh dreamchecker
        tools/bootstrap/python -c ''
    - name: Run DreamChecker
      shell: bash
      run: ~/dreamchecker 2>&1 | bash tools/ci/annotate_dm.sh
