# Creates an entry in html/changelogs automatically, to eventually be compiled by compile_changelogs
name: SS1984 Compile
on:
  - pull_request_target
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install OpenDream
      uses: robinraju/release-downloader@v1.12
      with:
        repository: "OpenDreamProject/OpenDream"
        tag: "latest"
        fileName: "DMCompiler_linux-x64.tar.gz"
        extract: true
    - name: Run OpenDream
      run: ./DMCompiler_linux-x64/DMCompiler tgstation.dme --suppress-unimplemented --define=CIBUILDING | bash tools/ci/annotate_od.sh
