name: Changelogs highlight SS1984

on:
  workflow_dispatch:
  workflow_call:

jobs:
  highlight:
    name: "Highlight SS1984 changes"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Check for ACTION_ENABLER secret and pass true to output if it exists to be checked by later steps"
        id: value_holder
        env:
          ENABLER_SECRET: ${{ secrets.ACTION_ENABLER }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "ACTIONS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT

      - name: "Setup python"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: "Install deps"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: "Checkout"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        uses: actions/checkout@v4
        with:
          fetch-depth: 25
          persist-credentials: false

      - name: "Compile"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        run: |
          python tools/ss1984_changelog_highlight.py

      - name: Commit
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        run: |
          git config --local user.name "1984-ci-event[bot]"
          git config --local user.email "1283078+1984-ci-event[bot]@users.noreply.github.com"
          git pull origin master
          git add tools/ss1984_changelog_highlight_generated.json
          git commit -m "SS1984 Automatic changelog highlight [ci skip]" -a || true

      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@v2
        if: env.APP_PRIVATE_KEY != '' && env.APP_ID != ''
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: "Push"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.app-token-generation.outputs.token || secrets.GITHUB_TOKEN }}
