# Creates an entry in html/changelogs automatically, to eventually be compiled by compile_changelogs
name: SS1984 DreamChecker
on:
  - pull_request_target
jobs:
  dreamchecker:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install DreamChecker
      run: |
        bash tools/ci/install_spaceman_dmm.sh dreamchecker
    - name: Run DreamChecker
      shell: bash
      run: ~/dreamchecker 2>&1 | bash tools/ci/annotate_dm.sh
